## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [3]:
df = pd.read_excel("aiml_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-06,2
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-29,3
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-10,0
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-09-22,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0%,Critical,36 more,Never,12
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25%,Critical,24 more,2026-10-06,2
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-09,1
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42%,Critical,16 more,2026-10-06,2
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-10,0
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-09-08,9
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17%,Critical,28 more,2026-10-06,2
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50%,Critical,12 more,2026-10-09,1
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33%,Critical,20 more,2026-10-06,2
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58%,Critical,8 more,2026-09-25,4
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-10,0
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-08,9

#### Section 1: Data Inspection

In [4]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
display(df.head(10))
display(df.shape)
display(df.dtypes)

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67%,Critical,4 more,2026-10-09,1
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8%,Critical,32 more,2026-09-22,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92%,Safe,✓ Met,2026-10-10,0
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100%,Safe,✓ Met,2026-10-10,0
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83%,Warning,✓ Met,2026-10-09,1
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75%,Warning,✓ Met,2026-10-09,1

(59, 12)

Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [5]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
#checking missing values in each column
df.isnull().sum()

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

In [7]:
#Identifying which columns hve null values
df.isnull().sum()[df.isnull().sum() > 0]

Series([], dtype: int64)

In [6]:
#count
df["Last Present Date"].eq("Never").sum()

np.int64(2)

In [26]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.columns = (df.columns.str.strip()
              .str.lower()
              .str.replace(" ", "_")
              .str.replace("%", "pct")
              .str.replace("(", "")
              .str.replace(")", ""))

df.columns.tolist()

['roll_no',
 'student_name',
 'subject',
 'total_classes',
 'present',
 'absent',
 'excused',
 'attendance_pct',
 'status',
 'classes_needed_75_pct',
 'last_present_date',
 'consecutive_absences',
 'attendance_category',
 'risk_score']

In [12]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------

"""Q4. Convert Attendance % to numeric float and Last Present Date to datetime, handling "Never" as NaT."""

df["attendance_pct"] = df["attendance_pct"].astype(float)

df["last_present_date"] = df["last_present_date"].replace("Never", pd.NaT)

df["last_present_date"] = pd.to_datetime(df["last_present_date"])

df[["attendance_pct", "last_present_date"]]

    attendance_pct last_present_date
0             67.0        2026-10-09
1             67.0        2026-10-09
2              8.0        2026-09-22
3             92.0        2026-10-10
4             83.0        2026-10-09
5             83.0        2026-10-09
6             83.0        2026-10-09
7            100.0        2026-10-10
8             83.0        2026-10-09
9             75.0        2026-10-09
10            75.0        2026-10-09
11            75.0        2026-10-06
12            50.0        2026-10-06
13            75.0        2026-10-09
14            92.0        2026-10-10
15            92.0        2026-10-09
16            92.0        2026-10-09
17            92.0        2026-10-09
18            25.0        2026-09-29
19            83.0        2026-10-10
20            83.0        2026-10-10
21            92.0        2026-10-10
22            17.0        2026-10-06
23            83.0        2026-10-06
24            75.0        2026-10-06
25            25.0        2026-09-22
26            92.0        2026-10-10
27            25.0        2026-10-06
28            83.0        2026-10-09
29            92.0        2026-10-10
30            25.0        2026-10-06
31            25.0        2026-10-06
32             0.0               NaT
33             0.0               NaT
34            83.0        2026-10-09
35             8.0        2026-10-06
36            33.0        2026-10-06
37            25.0        2026-10-06
38            92.0        2026-10-09
39            42.0        2026-10-06
40            75.0        2026-10-10
41            17.0        2026-09-08
42           100.0        2026-10-10
43            92.0        2026-10-10
44            17.0        2026-10-06
45            92.0        2026-10-10
46            83.0        2026-10-09
47            50.0        2026-10-09
48            83.0        2026-10-09
49            83.0        2026-10-06
50            75.0        2026-10-09
51            33.0        2026-10-06
52            83.0        2026-10-09
53            58.0        2026-09-25
54            67.0        2026-10-10
55            83.0        2026-10-09
56            83.0        2026-10-09
57            83.0        2026-10-06
58             8.0        2026-09-08

#### Section 2: Filtering & Selection

In [13]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
df[df["status"] == "Critical"].sort_values("attendance_pct")

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-22,5
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-10-06,2
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-08,9
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-09-08,9
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-22,5
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-29,3
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33.0,Critical,20 more,2026-10-06,2
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33.0,Critical,20 more,2026-10-06,2
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42.0,Critical,16 more,2026-10-06,2
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50.0,Critical,12 more,2026-10-09,1
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50.0,Critical,12 more,2026-10-06,2
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58.0,Critical,8 more,2026-09-25,4
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-09,1
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-09,1
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-10,0

In [14]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
df.loc[df["present"] == 0, ["roll_no", "student_name", "consecutive_absences"]]

       roll_no        student_name  consecutive_absences
32  4MW24AI035          RAJATH K K                    12
33  4MW24AI036  RAJU ASHOKA RATHOD                    12

In [16]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
# (a) All Safe students using .loc
df.loc[df["status"] == "Safe"]

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100.0,Safe,✓ Met,2026-10-10,0
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100.0,Safe,✓ Met,2026-10-10,0
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0

In [17]:

# (b) First 15 rows and columns 2-6 using .iloc
df.iloc[:15, 1:6]

,student_name,subject,total_classes,present,absent
0,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4
1,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4
2,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11
3,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1
4,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
5,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2
6,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
7,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0
8,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2
9,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3
10,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3
11,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3
12,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6
13,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3
14,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1

In [18]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
df.loc[df["consecutive_absences"] >= 5, ["student_name", "status", "last_present_date"]]

          student_name    status last_present_date
2               ADITYA  Critical        2026-09-22
25      MOURYA RAJ H N  Critical        2026-09-22
32          RAJATH K K  Critical               NaT
33  RAJU ASHOKA RATHOD  Critical               NaT
41             SHRAVYA  Critical        2026-09-08
58          Omkar Rane  Critical        2026-09-08

### Section 3: Grouping & Aggregation

In [19]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
)

          student_count  average_attendance  max_consecutive_absences
status
Critical             23           30.086957                        12
Safe                 13           93.230769                         1
Warning              23           80.565217                         2

In [20]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------


df["attendance_category"] = pd.cut(
    df["attendance_pct"],
    bins=[-1, 60, 75, 90, 100],
    labels=["Poor", "Average", "Good", "Excellent"],
    right=False
)

df.groupby("attendance_category", observed=False)["student_name"].count()

attendance_category
Poor         20
Average       3
Good         23
Excellent    11
Name: student_name, dtype: int64

In [21]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
df[["total_classes", "present", "absent"]].agg("sum")

total_classes    708
present          451
absent           257
dtype: int64

In [22]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
#a)min, max, and mean of Present
df.groupby("status")["present"].agg(["min", "max", "mean"])

          min  max       mean
status
Critical    0    8   3.608696
Safe       11   12  11.153846
Warning     9   10   9.695652

In [23]:
#b)sum of Absent
df.groupby("status")["absent"].agg("sum")

status
Critical    193
Safe         11
Warning      53
Name: absent, dtype: int64

### Section 4: Feature Engineering & Transformation

In [24]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df["risk_score"] = (df["absent"] * 0.4) + (df["consecutive_absences"] * 0.6)

df.sort_values("risk_score", ascending=False).head(10)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-08,9,Poor,9.8
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-09-08,9,Poor,9.4
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-22,5,Poor,7.4
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-22,5,Poor,6.6
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-10-06,2,Poor,5.6
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-29,3,Poor,5.4
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2,Poor,5.2
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2,Poor,5.2

In [28]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
df["classes_needed_numeric"] = df["classes_needed_75_pct"].str.extract(r"(\d+)").fillna(0).astype(int)

df[["classes_needed_75_pct", "classes_needed_numeric"]]

   classes_needed_75_pct  classes_needed_numeric
0                 4 more                       4
1                 4 more                       4
2                32 more                      32
3                  ✓ Met                       0
4                  ✓ Met                       0
5                  ✓ Met                       0
6                  ✓ Met                       0
7                  ✓ Met                       0
8                  ✓ Met                       0
9                  ✓ Met                       0
10                 ✓ Met                       0
11                 ✓ Met                       0
12               12 more                      12
13                 ✓ Met                       0
14                 ✓ Met                       0
15                 ✓ Met                       0
16                 ✓ Met                       0
17                 ✓ Met                       0
18               24 more                      24
19                 ✓ Met                       0
20                 ✓ Met                       0
21                 ✓ Met                       0
22               28 more                      28
23                 ✓ Met                       0
24                 ✓ Met                       0
25               24 more                      24
26                 ✓ Met                       0
27               24 more                      24
28                 ✓ Met                       0
29                 ✓ Met                       0
30               24 more                      24
31               24 more                      24
32               36 more                      36
33               36 more                      36
34                 ✓ Met                       0
35               32 more                      32
36               20 more                      20
37               24 more                      24
38                 ✓ Met                       0
39               16 more                      16
40                 ✓ Met                       0
41               28 more                      28
42                 ✓ Met                       0
43                 ✓ Met                       0
44               28 more                      28
45                 ✓ Met                       0
46                 ✓ Met                       0
47               12 more                      12
48                 ✓ Met                       0
49                 ✓ Met                       0
50                 ✓ Met                       0
51               20 more                      20
52                 ✓ Met                       0
53                8 more                       8
54                4 more                       4
55                 ✓ Met                       0
56                 ✓ Met                       0
57                 ✓ Met                       0
58               32 more                      32

In [29]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df["attendance_flag"] = df["attendance_pct"].apply(lambda x: "Defaulter" if x < 75 else "Safe")

df[["student_name", "attendance_pct", "attendance_flag"]]

                            student_name  attendance_pct attendance_flag
0                               ABHIJITH            67.0       Defaulter
1                     ABHISHEK KRISHNA P            67.0       Defaulter
2                                 ADITYA             8.0       Defaulter
3                      AKSHATA JAKAREDDY            92.0            Safe
4                                 ANANYA            83.0            Safe
5                            ANANYASHREE            83.0            Safe
6                  ANKITA TARANATH MESTA            83.0            Safe
7                      ANVITH S SHERIGAR           100.0            Safe
8                                APEKSHA            83.0            Safe
9                ARLENE VELORA FERNANDES            75.0            Safe
10                              ASHRITHA            75.0            Safe
11                         AYESHA REEMAN            75.0            Safe
12                     DHANRAJ L POOJARY            50.0       Defaulter
13                           DHANYATHA R            75.0            Safe
14                            G BHUPATHE            92.0            Safe
15                     HARSHAL G POOJARY            92.0            Safe
16                           JNANESH . S            92.0            Safe
17             KEERTHAN KRISHNA SHERIGAR            92.0            Safe
18                              KISHAN J            25.0       Defaulter
19                KUNDAR KASHISH CHANDRA            83.0            Safe
20                             LAKSHITHA            83.0            Safe
21                        MANEESH SHETTY            92.0            Safe
22                              MANMITHA            17.0       Defaulter
23                                 MAYUR            83.0            Safe
24                        MOHAMMED SIMAK            75.0            Safe
25                        MOURYA RAJ H N            25.0       Defaulter
26                       MUHAMMED NASHIT            92.0            Safe
27                                 NAVYA            25.0       Defaulter
28                        PAVITHRA NAYAK            83.0            Safe
29                             PRAGNYA R            92.0            Safe
30                          PRAMOD ACHAR            25.0       Defaulter
31                            RAJATH H S            25.0       Defaulter
32                            RAJATH K K             0.0       Defaulter
33                    RAJU ASHOKA RATHOD             0.0       Defaulter
34                          RAKESH HEGDE            83.0            Safe
35                                RASHMI             8.0       Defaulter
36                                RITHIN            33.0       Defaulter
37                                SANIKA            25.0       Defaulter
38                            SHAMANTH K            92.0            Safe
39               SHETTY RASHIK RATHNAKAR            42.0       Defaulter
40                      SHODAN B POOJARY            75.0            Safe
41                               SHRAVYA            17.0       Defaulter
42                    SHREESH A DEVADIGA           100.0            Safe
43                       SHRIYA DEVADIGA            92.0            Safe
44           SINCHANA (SUNDARA MADIVALA)            17.0       Defaulter
45  SINCHANA (MURALI KUPPAYYA MOGAVEERA)            92.0            Safe
46                              SPOORTHI            83.0            Safe
47                           SUPRAJA S M            50.0       Defaulter
48                              SUPRITHA            83.0            Safe
49                                 TEJAS            83.0            Safe
50                  TRIPTHI H PADMASHALI            75.0            Safe
51                                 VAMSH            33.0       Defaulter
52                               VANDANA            83.0            Safe
53                         VIGNESH ADIGA            58.0       Defaulter
54                              VIHAAN S            67.0       Defaulter
55                    YASHASVI K POOJARY            83.0            Safe
56                                Raksha            83.0            Safe
57                             Dhananjay            83.0            Safe
58                            Omkar Rane             8.0       Defaulter

In [30]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_range"] = pd.cut(
    df["attendance_pct"],
    bins=[0, 50, 75, 90, 100],
    labels=["Critical", "Warning", "Good", "Excellent"]
)

df[["student_name", "attendance_pct", "attendance_range"]]

                            student_name  attendance_pct attendance_range
0                               ABHIJITH            67.0          Warning
1                     ABHISHEK KRISHNA P            67.0          Warning
2                                 ADITYA             8.0         Critical
3                      AKSHATA JAKAREDDY            92.0        Excellent
4                                 ANANYA            83.0             Good
5                            ANANYASHREE            83.0             Good
6                  ANKITA TARANATH MESTA            83.0             Good
7                      ANVITH S SHERIGAR           100.0        Excellent
8                                APEKSHA            83.0             Good
9                ARLENE VELORA FERNANDES            75.0          Warning
10                              ASHRITHA            75.0          Warning
11                         AYESHA REEMAN            75.0          Warning
12                     DHANRAJ L POOJARY            50.0         Critical
13                           DHANYATHA R            75.0          Warning
14                            G BHUPATHE            92.0        Excellent
15                     HARSHAL G POOJARY            92.0        Excellent
16                           JNANESH . S            92.0        Excellent
17             KEERTHAN KRISHNA SHERIGAR            92.0        Excellent
18                              KISHAN J            25.0         Critical
19                KUNDAR KASHISH CHANDRA            83.0             Good
20                             LAKSHITHA            83.0             Good
21                        MANEESH SHETTY            92.0        Excellent
22                              MANMITHA            17.0         Critical
23                                 MAYUR            83.0             Good
24                        MOHAMMED SIMAK            75.0          Warning
25                        MOURYA RAJ H N            25.0         Critical
26                       MUHAMMED NASHIT            92.0        Excellent
27                                 NAVYA            25.0         Critical
28                        PAVITHRA NAYAK            83.0             Good
29                             PRAGNYA R            92.0        Excellent
30                          PRAMOD ACHAR            25.0         Critical
31                            RAJATH H S            25.0         Critical
32                            RAJATH K K             0.0              NaN
33                    RAJU ASHOKA RATHOD             0.0              NaN
34                          RAKESH HEGDE            83.0             Good
35                                RASHMI             8.0         Critical
36                                RITHIN            33.0         Critical
37                                SANIKA            25.0         Critical
38                            SHAMANTH K            92.0        Excellent
39               SHETTY RASHIK RATHNAKAR            42.0         Critical
40                      SHODAN B POOJARY            75.0          Warning
41                               SHRAVYA            17.0         Critical
42                    SHREESH A DEVADIGA           100.0        Excellent
43                       SHRIYA DEVADIGA            92.0        Excellent
44           SINCHANA (SUNDARA MADIVALA)            17.0         Critical
45  SINCHANA (MURALI KUPPAYYA MOGAVEERA)            92.0        Excellent
46                              SPOORTHI            83.0             Good
47                           SUPRAJA S M            50.0         Critical
48                              SUPRITHA            83.0             Good
49                                 TEJAS            83.0             Good
50                  TRIPTHI H PADMASHALI            75.0          Warning
51                                 VAMSH            33.0         Critical
52                               VANDANA            83.0             Good
53                         VIGNESH ADIGA            58.0          Warning
54                              VIHAAN S            67.0          Warning
55                    YASHASVI K POOJARY            83.0             Good
56                                Raksha            83.0             Good
57                             Dhananjay            83.0             Good
58                            Omkar Rane             8.0         Critical

### Section 5: Advanced Analysis

In [31]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
df.pivot_table(
    index="status",
    columns="attendance_category",
    values="student_name",
    aggfunc="count",
    fill_value=0
)

attendance_category  Poor  Average  Good  Excellent
status
Critical               20        3     0          0
Safe                    0        0     0         11
Warning                 0        0    23          0

In [32]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
df["base_name"] = df["student_name"].str.split().str[0]

duplicate_names = df[df.duplicated("base_name", keep=False)]

duplicate_names

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,RAJATH
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,NaN,RAJATH
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,SINCHANA
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,SINCHANA

In [33]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
Student_Details = pd.DataFrame({
    "roll_no": df["roll_no"],
    "branch": "AIML",
    "semester": 5
})

merged_df = pd.merge(df, Student_Details, on="roll_no", how="inner")

merged_df

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name,branch,semester
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-09,1,Average,2.2,4,Defaulter,Warning,ABHIJITH,AIML,5
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-09,1,Average,2.2,4,Defaulter,Warning,ABHISHEK,AIML,5
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-22,5,Poor,7.4,32,Defaulter,Critical,ADITYA,AIML,5
3,4MW24AI004,AKSHATA JAKAREDDY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,AKSHATA,AIML,5
4,4MW24AI005,ANANYA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,ANANYA,AIML,5
5,4MW24AI006,ANANYASHREE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,ANANYASHREE,AIML,5
6,4MW24AI007,ANKITA TARANATH MESTA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,ANKITA,AIML,5
7,4MW24AI008,ANVITH S SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100.0,Safe,✓ Met,2026-10-10,0,NaN,0.0,0,Safe,Excellent,ANVITH,AIML,5
8,4MW24AI009,APEKSHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,APEKSHA,AIML,5
9,4MW24AI010,ARLENE VELORA FERNANDES,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75.0,Warning,✓ Met,2026-10-09,1,Good,1.8,0,Safe,Warning,ARLENE,AIML,5
10,4MW24AI011,ASHRITHA,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75.0,Warning,✓ Met,2026-10-09,1,Good,1.8,0,Safe,Warning,ASHRITHA,AIML,5
11,4MW24AI013,AYESHA REEMAN,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75.0,Warning,✓ Met,2026-10-06,2,Good,2.4,0,Safe,Warning,AYESHA,AIML,5
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50.0,Critical,12 more,2026-10-06,2,Poor,3.6,12,Defaulter,Critical,DHANRAJ,AIML,5
13,4MW24AI015,DHANYATHA R,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75.0,Warning,✓ Met,2026-10-09,1,Good,1.8,0,Safe,Warning,DHANYATHA,AIML,5
14,4MW24AI016,G BHUPATHE,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,G,AIML,5
15,4MW24AI018,HARSHAL G POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1,Excellent,1.0,0,Safe,Excellent,HARSHAL,AIML,5
16,4MW24AI019,JNANESH . S,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1,Excellent,1.0,0,Safe,Excellent,JNANESH,AIML,5
17,4MW24AI020,KEERTHAN KRISHNA SHERIGAR,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1,Excellent,1.0,0,Safe,Excellent,KEERTHAN,AIML,5
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-29,3,Poor,5.4,24,Defaulter,Critical,KISHAN,AIML,5
19,4MW24AI022,KUNDAR KASHISH CHANDRA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-10,0,Good,0.8,0,Safe,Good,KUNDAR,AIML,5
20,4MW24AI023,LAKSHITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-10,0,Good,0.8,0,Safe,Good,LAKSHITHA,AIML,5
21,4MW24AI024,MANEESH SHETTY,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,MANEESH,AIML,5
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,MANMITHA,AIML,5
23,4MW24AI026,MAYUR,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-06,2,Good,2.0,0,Safe,Good,MAYUR,AIML,5
24,4MW24AI027,MOHAMMED SIMAK,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75.0,Warning,✓ Met,2026-10-06,2,Good,2.4,0,Safe,Warning,MOHAMMED,AIML,5
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-22,5,Poor,6.6,24,Defaulter,Critical,MOURYA,AIML,5
26,4MW24AI029,MUHAMMED NASHIT,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,MUHAMMED,AIML,5
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,NAVYA,AIML,5
28,4MW24AI031,PAVITHRA NAYAK,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,PAVITHRA,AIML,5
29,4MW24AI032,PRAGNYA R,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,PRAGNYA,AIML,5
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,PRAMOD,AIML,5
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,RAJATH,AIML,5
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,NaN,RAJATH,AIML,5
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,NaN,RAJU,AIML,5
34,4MW24AI037,RAKESH HEGDE,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,RAKESH,AIML,5
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-10-06,2,Poor,5.6,32,Defaulter,Critical,RASHMI,AIML,5
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33.0,Critical,20 more,2026-10-06,2,Poor,4.4,20,Defaulter,Critical,RITHIN,AIML,5
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,SANIKA,AIML,5
38,4MW24AI042,SHAMANTH K,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,1,Excellent,1.0,0,Safe,Excellent,SHAMANTH,AIML,5
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42.0,Critical,16 more,2026-10-06,2,Poor,4.0,16,Defaulter,Critical,SHETTY,AIML,5
40,4MW24AI044,SHODAN B POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75.0,Warning,✓ Met,2026-10-10,0,Good,1.2,0,Safe,Warning,SHODAN,AIML,5
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-09-08,9,Poor,9.4,28,Defaulter,Critical,SHRAVYA,AIML,5
42,4MW24AI046,SHREESH A DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,12,0,0,100.0,Safe,✓ Met,2026-10-10,0,NaN,0.0,0,Safe,Excellent,SHREESH,AIML,5
43,4MW24AI047,SHRIYA DEVADIGA,Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,SHRIYA,AIML,5
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,SINCHANA,AIML,5
45,4MW24AI049,SINCHANA (MURALI KUPPAYYA MOGAVEERA),Data Science & GenAI - 3nd Yr- AIML,12,11,1,0,92.0,Safe,✓ Met,2026-10-10,0,Excellent,0.4,0,Safe,Excellent,SINCHANA,AIML,5
46,4MW24AI050,SPOORTHI,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,SPOORTHI,AIML,5
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50.0,Critical,12 more,2026-10-09,1,Poor,3.0,12,Defaulter,Critical,SUPRAJA,AIML,5
48,4MW24AI053,SUPRITHA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,SUPRITHA,AIML,5
49,4MW24AI054,TEJAS,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-06,2,Good,2.0,0,Safe,Good,TEJAS,AIML,5
50,4MW24AI055,TRIPTHI H PADMASHALI,Data Science & GenAI - 3nd Yr- AIML,12,9,3,0,75.0,Warning,✓ Met,2026-10-09,1,Good,1.8,0,Safe,Warning,TRIPTHI,AIML,5
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33.0,Critical,20 more,2026-10-06,2,Poor,4.4,20,Defaulter,Critical,VAMSH,AIML,5
52,4MW24AI057,VANDANA,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,VANDANA,AIML,5
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58.0,Critical,8 more,2026-09-25,4,Poor,4.4,8,Defaulter,Warning,VIGNESH,AIML,5
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-10,0,Average,1.6,4,Defaulter,Warning,VIHAAN,AIML,5
55,4MW24AI060,YASHASVI K POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,YASHASVI,AIML,5
56,4MW24AI061,Raksha,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,1,Good,1.4,0,Safe,Good,Raksha,AIML,5
57,4MW25AI400,Dhananjay,Data Science & GenAI - 3nd Yr- AIML,12,10,2,0,83.0,Warning,✓ Met,2026-10-06,2,Good,2.0,0,Safe,Good,Dhananjay,AIML,5
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-08,9,Poor,9.8,32,Defaulter,Critical,Omkar,AIML,5

In [38]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------
#(a) All "Critical" students
critical_students = df[df["status"] == "Critical"]
critical_students.to_csv("critical_students.csv", index=False)
display(critical_students)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
0,4MW24AI001,ABHIJITH,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-09,1,Average,2.2,4,Defaulter,Warning,ABHIJITH
1,4MW24AI002,ABHISHEK KRISHNA P,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-09,1,Average,2.2,4,Defaulter,Warning,ABHISHEK
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-22,5,Poor,7.4,32,Defaulter,Critical,ADITYA
12,4MW24AI014,DHANRAJ L POOJARY,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50.0,Critical,12 more,2026-10-06,2,Poor,3.6,12,Defaulter,Critical,DHANRAJ
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-29,3,Poor,5.4,24,Defaulter,Critical,KISHAN
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,MANMITHA
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-22,5,Poor,6.6,24,Defaulter,Critical,MOURYA
27,4MW24AI030,NAVYA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,NAVYA
30,4MW24AI033,PRAMOD ACHAR,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,PRAMOD
31,4MW24AI034,RAJATH H S,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,RAJATH
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,NaN,RAJATH
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,NaN,RAJU
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-10-06,2,Poor,5.6,32,Defaulter,Critical,RASHMI
36,4MW24AI039,RITHIN,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33.0,Critical,20 more,2026-10-06,2,Poor,4.4,20,Defaulter,Critical,RITHIN
37,4MW24AI041,SANIKA,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-10-06,2,Poor,4.8,24,Defaulter,Critical,SANIKA
39,4MW24AI043,SHETTY RASHIK RATHNAKAR,Data Science & GenAI - 3nd Yr- AIML,12,5,7,0,42.0,Critical,16 more,2026-10-06,2,Poor,4.0,16,Defaulter,Critical,SHETTY
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-09-08,9,Poor,9.4,28,Defaulter,Critical,SHRAVYA
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,SINCHANA
47,4MW24AI052,SUPRAJA S M,Data Science & GenAI - 3nd Yr- AIML,12,6,6,0,50.0,Critical,12 more,2026-10-09,1,Poor,3.0,12,Defaulter,Critical,SUPRAJA
51,4MW24AI056,VAMSH,Data Science & GenAI - 3nd Yr- AIML,12,4,8,0,33.0,Critical,20 more,2026-10-06,2,Poor,4.4,20,Defaulter,Critical,VAMSH
53,4MW24AI058,VIGNESH ADIGA,Data Science & GenAI - 3nd Yr- AIML,12,7,5,0,58.0,Critical,8 more,2026-09-25,4,Poor,4.4,8,Defaulter,Warning,VIGNESH
54,4MW24AI059,VIHAAN S,Data Science & GenAI - 3nd Yr- AIML,12,8,4,0,67.0,Critical,4 more,2026-10-10,0,Average,1.6,4,Defaulter,Warning,VIHAAN
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-08,9,Poor,9.8,32,Defaulter,Critical,Omkar

In [39]:
#(b) Summary statistics grouped by Status
summary = df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
)

summary.to_csv("status_summary.csv")
display(summary)

          student_count  average_attendance  max_consecutive_absences
status
Critical             23           30.086957                        12
Safe                 13           93.230769                         1
Warning              23           80.565217                         2

In [40]:
#(c) Top 10 students by Risk Score
top_10 = df.sort_values("risk_score", ascending=False).head(10)
top_10.to_csv("top_10_risk_students.csv", index=False)
display(top_10)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
33,4MW24AI036,RAJU ASHOKA RATHOD,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,NaN,RAJU
32,4MW24AI035,RAJATH K K,Data Science & GenAI - 3nd Yr- AIML,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,NaN,RAJATH
58,4MW25AI401,Omkar Rane,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-08,9,Poor,9.8,32,Defaulter,Critical,Omkar
41,4MW24AI045,SHRAVYA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-09-08,9,Poor,9.4,28,Defaulter,Critical,SHRAVYA
2,4MW24AI003,ADITYA,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-09-22,5,Poor,7.4,32,Defaulter,Critical,ADITYA
25,4MW24AI028,MOURYA RAJ H N,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-22,5,Poor,6.6,24,Defaulter,Critical,MOURYA
35,4MW24AI038,RASHMI,Data Science & GenAI - 3nd Yr- AIML,12,1,11,0,8.0,Critical,32 more,2026-10-06,2,Poor,5.6,32,Defaulter,Critical,RASHMI
18,4MW24AI021,KISHAN J,Data Science & GenAI - 3nd Yr- AIML,12,3,9,0,25.0,Critical,24 more,2026-09-29,3,Poor,5.4,24,Defaulter,Critical,KISHAN
22,4MW24AI025,MANMITHA,Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,MANMITHA
44,4MW24AI048,SINCHANA (SUNDARA MADIVALA),Data Science & GenAI - 3nd Yr- AIML,12,2,10,0,17.0,Critical,28 more,2026-10-06,2,Poor,5.2,28,Defaulter,Critical,SINCHANA